### PR TITLE
Update for Iceborne

### PR DESCRIPTION
**Pull request by aria-zivar**
Hoi~

Updated the shop editor to handle the new shop list format for Iceborne. :>

### CODE REVIEW

**Comment by JSLJ23** [comment]
So does it now work for Iceborne?

**Comment by aria-zivar** [comment]
> So does it now work for Iceborne?

Only if you can read the title of the PR.

**Comment by JSLJ23** [comment]
I put the shopList.slt file in Monster Hunter World\nativePC\common\facility but it still does not show up in game.

**Comment by aria-zivar** [comment]
> I put the shopList.slt file in Monster Hunter World\nativePC\common\facility but it still does not show up in game.
By default the game only loads visual files unless you're using Stracker's Loader so it redirects any nativePC mods that aren't visual files.

**Comment by IX-Xur** [comment]
I appreciate the effort here, and good job on it. I already have the program updated, with some new features too, but its currently in testing on my Patreon before a public release. It'll launch publicly by the end of the week.

**Pull request closed without merging**
